Uses the way how _WidgetsLocalizationsDelegate choose an appropriate …
firebase/FirebaseUI-Flutter pull request #128
Opened 2023-10-05 01:14 UTC by gary6lin

## Description

I found that the `firebase_ui_localizations` package includes a translation for Taiwan (`ZhTWLocalizations`), but has not been used appropriately. So I follow the same approach of how the `flutter_localizations` package gets the appropriate translation and how to fallback when the `scriptCode` or `countryCode` is not defined.

## Related Issues

The other people also encounter the [same issue](https://github.com/firebase/FirebaseUI-Flutter/issues/33) as me.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/contributing.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-10-05 12:22 UTC, lesnitsky requested changes

2023-10-05 12:22 UTC, lesnitsky commented on packages/firebase_ui_localizations/lib/src/all_languages.dart
> +    [Locale? defaultLocale]) {
add trailing comma

2023-10-05 12:23 UTC, lesnitsky commented
@gary6lin Thanks for submitting a PR! Could you please add unit tests verifying that traditional Chinese loads correctly now?  Also might be good to add a test verifying that localization overrides still work.

2023-10-06 03:41 UTC, gary6lin commented
Trailing comma and test cases added.

2023-10-09 12:20 UTC, lesnitsky approved these changes

2023-10-09 12:21 UTC, lesnitsky requested changes

2023-10-09 12:21 UTC, lesnitsky commented on packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart
> +          final localizations = await delegate.load(localeZh);
could we have a widget test here instead? So something along these lines:

```
testWidgets('...', (tester) async {
  await tester.pumpWidget(
    MaterialApp(
      locale: Locale('zh'),
      ...
    )
  );
  
  expect(find.text('some translated label'), expected);
});

// same test, but for `zh-tw`

// widget test for label overrides

2023-10-11 11:08 UTC, lesnitsky requested changes

2023-10-11 11:08 UTC, lesnitsky commented on packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart
> +  final String Function(BuildContext context) localizedText;
`localizedText` sounds more like a data property, not a function, maybe `localizeText` is a better name

2023-10-11 11:08 UTC, lesnitsky commented on packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart
> +  Widget build(BuildContext context) => MaterialApp(
convert to block body

2023-10-11 11:13 UTC, lesnitsky commented
@gary6lin could you please run `melos run format` to make `code_health/format` green.

2023-10-11 14:47 UTC, lesnitsky requested changes

2023-10-11 14:58 UTC, gary6lin commented on packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart
> +      localizedText(BuildContext context) =>
Sure thing :)
Btw, do you have any tips for using block or expression body? Cus I use the expression body quite often.
I only use the block body if I find the result of `dart format` is too ugly.

2023-10-11 15:18 UTC, lesnitsky commented on packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart
> +      localizedText(BuildContext context) =>
I prefer using block body when expression doesn't fit a single line and actual body gets moved to the next line

2023-10-11 23:20 UTC, lesnitsky approved these changes

2023-10-11 23:20 UTC, merged