chore: move docs to repo root
firebase/FirebaseUI-Flutter pull request #129
Opened 2023-10-05 13:32 UTC by lesnitsky

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/contributing.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-10-05 13:52 UTC, russellwheatley requested changes

2023-10-05 13:52 UTC, russellwheatley commented on docs/firebase-ui-localizations.md
> +# Firebase UI LOcalizations
```suggestion
# Firebase UI Localizations
```

2023-10-05 13:52 UTC, russellwheatley commented on docs/firebase-ui-firestore.md
> +With more power comes more responsibility:
I doubt they'll allow this on Firebase docs. I'd make it a sub-header with something along the lines of "manually fetching data within `GridView` implementation"

2023-10-05 13:52 UTC, russellwheatley commented on docs/firebase-ui-database.md
> +With more power comes more responsibility:
same

2023-10-05 13:58 UTC, russellwheatley approved these changes

2023-10-09 11:53 UTC, Lyokone approved these changes

2023-10-09 11:53 UTC, exaby73 approved these changes

2023-10-09 11:53 UTC, merged