feat(example): add display name screen when user register
firebase/FirebaseUI-Flutter pull request #82
Opened 2023-08-24 18:01 UTC by YassinNouh21

## Description

This PR enhances the ```SignInScreen``` widget by adding a new feature. When the `displayName` property of the user is found to be `null`, the app will now navigate the user to a screen titled "What is your name?" where they can input or edit their display name. This feature provides a more user-friendly.

## Related Issues

This is based on [Discussed in 69](https://github.com/firebase/FirebaseUI-Flutter/discussions/69) and [Issue 76 ](https://github.com/firebase/FirebaseUI-Flutter/issues/76)for enhancement 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/contributing.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-09-23 14:07 UTC, YassinNouh21 reviewed
Thank you for your feedback, I just add in the screen folder new screen `DisplayNameScreen` with its text controller `EditableSignUserDisplayName` and added action for navigating when user finishes typing his name

2023-10-02 11:54 UTC, lesnitsky requested changes

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/actions.dart
> +import 'package:flutter/material.dart';
This change is irrelevant to the PR's main goal.

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/screens/display_name_screen.dart
> +class DisplayNameAction extends FirebaseUIAction {
I'm not sure what this action does and the doc comment is confusing. Why is it called after sign up but called `DisplayNameAction`?

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/screens/display_name_screen.dart
> +  void _sendEmailVerification(_) {
Why this screen has anything to do with the email verification?

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/screens/display_name_screen.dart
> +        EditableSignUserDisplayName(auth: auth),
there is an existing widget: [`EditableUserDisplayName`](https://pub.dev/documentation/firebase_ui_auth/latest/firebase_ui_auth/EditableUserDisplayName-class.html)

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/screens/display_name_screen.dart
> +            l.name,
this label is used in a different context and might change, this screen needs its own label (`editableDisplayNameTitle`). Currently adding a new label is a bit tedious, but there are a few improvements to this process in #116, so it's worth waiting for it to be merged first.

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/screens/display_name_screen.dart
> +      ],
This screen needs `continue` and `go back` buttons. With current implementation, if `DisplayNameChanged` action is not provided – the user will be stuck on this screen. I'm doubting that we need this action at all. `continue` and `go back` buttons should be enough.

2023-10-02 11:54 UTC, lesnitsky commented on packages/firebase_ui_auth/lib/src/widgets/editable_sign_user_display_name.dart
> +class EditableSignUserDisplayName extends StatefulWidget {
https://pub.dev/documentation/firebase_ui_auth/latest/firebase_ui_auth/EditableUserDisplayName-class.html

2023-10-09 11:57 UTC, lesnitsky commented
@YassinNouh21 would you be willing to address my feedback?

2023-10-19 11:32 UTC, lesnitsky commented
@YassinNouh21 any updates on this PR?

2023-10-19 19:14 UTC, YassinNouh21 commented
> @YassinNouh21 any updates on this PR?

Sorry I been busy this week I will finish it by the weekend

2023-11-23 14:59 UTC, lesnitsky commented
@YassinNouh21 any updates on this?

2023-11-29 18:36 UTC, closed without merging

2024-02-12 13:56 UTC, bakua commented
Shame :/